[Autologin]
# Whether sddm should automatically log back into sessions when they exit
Relogin=false

# Name of session file for autologin session (if empty try last logged in)
Session=

# Username for autologin session
User=

[General]
# Reboot command
RebootCommand=/usr/bin/systemctl reboot

[Theme]
# Current theme name
Current=where_is_my_sddm_theme

# Font used in the greeter
Font=Monocraft

# Theme directory path
ThemeDir=/usr/share/sddm/themes

# Maximum user id for displayed users
MaximumUid=60513

# Minimum user id for displayed users
MinimumUid=1000

# Remember the session of the last successfully logged in user
RememberLastSession=true

# Remember the last successfully logged in user
RememberLastUser=true

# When logging in as the same user twice, restore the original session, rather than create a new one
ReuseSession=true
