# ▗▄▄▄  ▗▞▀▚▖▗▞▀▘ ▄▄▄   ▄▄▄ ▗▞▀▜▌   ■  ▄  ▄▄▄  ▄▄▄▄
# ▐▌  █ ▐▛▀▀▘▝▚▄▖█   █ █    ▝▚▄▟▌▗▄▟▙▄▖▄ █   █ █   █
# ▐▌  █ ▝▚▄▄▖    ▀▄▄▄▀ █           ▐▌  █ ▀▄▄▄▀ █   █
# ▐▙▄▄▀                            ▐▌  █
#                                  ▐▌
source = noctalia/noctalia-colors.conf

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
}

general {
    col.active_border = $primary $tertiary
    col.inactive_border = $surface $tertiary
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
        text_color = $surface_lowest
        text_color_inactive = $tertiary
    }
}

decoration {
    active_opacity = 0.95
    inactive_opacity = 0.95
    rounding = 10
    dim_inactive = true
    dim_strength = 0.2

    shadow {
    enabled = true
    }

    blur {
        enabled = yes
        size = 6
        passes = 1
        new_optimizations = on
        xray = true
        popups = true
        input_methods = true
        ignore_opacity = true
    }
}
