# ▗▄▄▄▖▄   ▄ ▗▞▀▘▗▞▀▚▖
# ▐▌    ▀▄▀  ▝▚▄▖▐▛▀▀▘
# ▐▛▀▀▘▄▀ ▀▄     ▝▚▄▄▖
# ▐▙▄▄▖

exec-once = push-to-talk -k KEY_RIGHTALT -n Alt_R /dev/input/by-path/platform-i8042-serio-0-event-kbd
exec-once = qs -c noctalia-shell
exec-once = hyprpm reload
exec-once = kdeconnectd
exec-once = fcitx5 -d
exec-once = uwsm finalize
