# ▗▖  ▗▖▄  ▄▄▄ ▗▞▀▜▌▄     ▗▖  ▗▖▄ █  ▄ █  ▄ ▄
# ▐▛▚▞▜▌▄ █    ▝▚▄▟▌▄     ▐▛▚▖▐▌▄ █▄▀  █▄▀  ▄
# ▐▌  ▐▌█ █         █     ▐▌ ▝▜▌█ █ ▀▄ █ ▀▄ █
# ▐▌  ▐▌█           █     ▐▌  ▐▌█ █  █ █  █ █

source = ./env.conf
source = ./exec.conf
source = ./misc.conf
source = ./input.conf
source = ./monitors.conf
source = ./layerrules.conf
source = ./keybindings.conf
source = ./windowrules.conf
source = ./animation.conf
source = noctalia/noctalia-colors.conf
source = ./decoration.conf
