# ▗▄▄▄▖▄▄▄▄  ▄▄▄▄  █  ▐▌   ■
#   █  █   █ █   █ ▀▄▄▞▘▗▄▟▙▄▖
#   █  █   █ █▄▄▄▀        ▐▌
# ▗▄█▄▖      █            ▐▌
#            ▀            ▐▌

input {
    kb_layout = us
    repeat_rate = 50
    repeat_delay = 300
    follow_mouse = true
    float_switch_override_focus = false
    follow_mouse = 1
    sensitivity = 0.3
    accel_profile = adaptive

touchpad {
    natural_scroll = true
    disable_while_typing = false
    tap-to-click = true
    tap-and-drag = true
    drag_lock = false
    clickfinger_behavior = false
    middle_button_emulation = true
    scroll_factor = 0.9
    }

# Touchpad Gestures
gesture = 3, horizontal, workspace
gesture = 4, down, close
gesture = 4, up, fullscreen

touchdevice {
    enabled = true
    }
}
