# ▗▖  ▗▖▄  ▄▄▄ ▗▞▀▘
# ▐▛▚▞▜▌▄ ▀▄▄  ▝▚▄▖
# ▐▌  ▐▌█ ▄▄▄▀
# ▐▌  ▐▌█

# Switches
bindl = , switch:on:Lid Switch, exec, qs -c noctalia-shell ipc call lockScreen lock

general {
    layout = dwindle
    resize_on_border = true
    no_focus_fallback = true
    allow_tearing = true
    snap {
    	enabled = true
    }
}

dwindle {
    #smart_split = true
    #smart_resizing = true
    precise_mouse_move = true
}

group{
        groupbar{
            enabled = true
            height = 22
            font_size = 16
            blur = true
            gradients = true
            gradient_rounding = 10
            rounding = 10
            indicator_height = 0
            keep_upper_gap = false
            font_family = Monocraft
    }
}

ecosystem {
    no_update_news = true
    no_donation_nag = true
}

misc {
    anr_missed_pings = 5
    enable_swallow = true
    focus_on_activate = false
    swallow_regex = ^(kitty)$
    middle_click_paste = false
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    animate_manual_resizes = true
    key_press_enables_dpms = true
    mouse_move_enables_dpms = true
    initial_workspace_tracking = 1
    disable_splash_rendering = true
    allow_session_lock_restore = true
}

binds {
  workspace_back_and_forth = true
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
}

xwayland {
    enabled = true
    force_zero_scaling = true
}

render {
  direct_scanout = false
}
