# ▗▖ ▗▖▄ ▄▄▄▄     ▐▌ ▄▄▄  ▄   ▄ ▗▄▄▖ █  ▐▌█ ▗▞▀▚▖ ▄▄▄
# ▐▌ ▐▌▄ █   █    ▐▌█   █ █ ▄ █ ▐▌ ▐▌▀▄▄▞▘█ ▐▛▀▀▘▀▄▄
# ▐▌ ▐▌█ █   █ ▗▞▀▜▌▀▄▄▄▀ █▄█▄█ ▐▛▀▚▖     █ ▝▚▄▄▖▄▄▄▀
# ▐▙█▟▌█       ▝▚▄▟▌            ▐▌ ▐▌     █

# Idle Inhibit
windowrule = idle_inhibit fullscreen true, match:content 2 3

# Size
windowrule = size 790 600,match:class ^(org.freedesktop.impl.portal.desktop.kde)$
windowrule = size 550 575,match:class ^(qt6ct)$
windowrule = size 550 575,match:class ^(qt5ct)$

# Picture-in-Picture
windowrule {
    name = picture_in_picture
    match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
    tag = +picture-in-picture
    float = true
    keep_aspect_ratio = true
    move = (monitor_w*0.666) (monitor_h*0.69)
    size = (monitor_w*0.30) (monitor_h*0.30)
    pin = true
}

# No Decoration
windowrule = no_blur on, match:content 2 3
windowrule = no_dim on, match:content 2 3
windowrule = no_shadow on, match:content 2 3
windowrule = no_anim on, match:content 2 3

# Float
windowrule = float true,match:class ^(qt5ct)$
windowrule = float true,match:class ^(qt6ct)$
windowrule = float true,match:class ^(org.freedesktop.impl.portal.desktop.kde)$
windowrule = float true,match:class ^(io.github.kaii_lb.Overskride)$
windowrule = float true,match:class ^(swayimg)$
windowrule = float true,match:class ^(com.gabm.satty)$
windowrule = float true,match:class ^(yad)$ # Protontricks-Gtk
windowrule = float true,match:title ^(Friends List)$ # Steam Friends List
windowrule = float true,match:title ^(Steam Settings)$ # Steam Settings
